# .air.toml
[build]
    full_bin = "go run main.go --SERVER_HOST=$SERVER_HOST --SERVER_PORT=$SERVER_PORT --REDIS_URL=$REDIS_URL --PG_URL=$PG_URL --MODE=$MODE --DEBUG=$DEBUG --REDIS_QUEUE_MAX_SIZE=$REDIS_QUEUE_MAX_SIZE"
